# النسخة القياسية الرسمية - بدون أي مسارات يدوية مخربة
import_path = File.expand_path(File.join('..', '..', '..', 'packages', 'flutter_tools', 'bin', 'podhelper.rb'), __FILE__)
# في فلاتر المسار الافتراضي بكون هيك بالظبط:
require File.expand_path(File.join('..', '..', '..', 'packages', 'flutter_tools', 'bin', 'podhelper.rb'), __FILE__)

platform :ios, '13.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # هاد السطر بس اللي بهمنا عشان الفايربيز مسجنج ينجح بالـ Xcode
  pod 'FirebaseMessaging', :modular_headers => true

  flutter_ios_podfile_setup
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    target.build_configurations.each do |config|
      # هذا الأمر بجبر الـ Xcode يطنش الـ non-modular headers ويمشي البيلد لآخر خطوة
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
  end
end